### ISSUE TITLE
[支持双拼] 能支持百度的小鹤双拼模式么

### ISSUE THREAD

**Issue by hiberabyss** [ZSaberLv0/ZFVimIM_openapi#1]

**Comment by ZSaberLv0** [comment]
目前只有 olime.baidu.com 还可用, 这玩意儿似乎只支持拼音
如果有什么更好的源欢迎 PR

**Comment by hiberabyss** [comment]
可以通过映射的方式来做，我来实现下吧

**Comment by ZSaberLv0** [comment]
那不如直接用词库，搜了下有人弄过，你可以试试
https://github.com/qdzhang/ZFVimIM_xiaohe
https://github.com/Yiklek/ZFVimIM_openfly

**Comment by hiberabyss** [comment]
> 那不如直接用词库，搜了下有人弄过，你可以试试 https://github.com/qdzhang/ZFVimIM_xiaohe https://github.com/Yiklek/ZFVimIM_openfly

这里能支持把选择的  百度云  里的词也记录到词库里么？

**Comment by hiberabyss** [comment]
我现在已经支持通过百度云查询双拼的词了，但现在需要能把云里的词保存在我自己的词库里，这样能比较方便地积累自己的词库。

**Comment by ZSaberLv0** [comment]
https://github.com/ZSaberLv0/ZFVimIM/blob/f78507f91f1cef15a089f9ffa77977ca145f5a34/plugin/ZFVimIM_API.vim#L224

可以根据需要 `ZFVimIM_wordAdd(db, word, key)` 添加自定义词, 会自动同步词库

**Comment by hiberabyss** [comment]
> https://github.com/ZSaberLv0/ZFVimIM/blob/f78507f91f1cef15a089f9ffa77977ca145f5a34/plugin/ZFVimIM_API.vim#L224
> 
> 可以根据需要 `ZFVimIM_wordAdd(db, word, key)` 添加自定义词, 会自动同步词库

那这里可以通过什么事件判断选取了 cloud 里的词，然后执行相应的动作呢？

**Comment by ZSaberLv0** [comment]
更新一下 https://github.com/ZSaberLv0/ZFVimIM/commit/9ba3192880bf2a7f04e5451a318a9b2764289324

然后:

``` vim
let s:MyUserWord = []
autocmd User ZFVimIM_event_OnCompleteDone call s:OnCompleteDone()

function! s:OnCompleteDone()
    call add(s:MyUserWord, g:ZFVimIM_choosedWord)
    if g:ZFVimIM_choosedWord['len'] == len(ZFVimIME_state()['key'])
        " TODO: 根据你的需求, 组词并添加自定义词库
        echomsg 'add my user word:'
        echomsg s:MyUserWord
        let key = xxxx
        let word = xxxx
        call ZFVimIM_wordAdd({}, word, key)

        let s:MyUserWord = []
    endif
endfunction
```

监听 `:h CompleteDone` 和 `:h v:completed_item` 效果也差不多, 但旧版本 vim 没有这些

**Comment by hiberabyss** [comment]
Thanks!
