### ISSUE TITLE
[支持五笔]这个 openapi 可以支持五笔输入法么

### ISSUE THREAD

**Issue by TMTBO** [ZSaberLv0/ZFVimIM_openapi#3]
找了一圈没找到相关文档🙃

**Comment by ZSaberLv0** [comment]
这玩意儿是curl调用百度云输入的开放接口来实现的，目前没发现有支持五笔的开放接口
另一种思路是用各种方式和系统输入法通讯，但目前也没发现有啥系统输入法支持外部调用

**Comment by TMTBO** [comment]
OK, 没问题的, 我昨天也是找了一圈, 没找开这个开放接口的文档, 我去看看能不能把openai 用起来😃
